<<<<<<< HEAD
name: flemini
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.6
  http: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  icons_launcher: ^2.1.7
  



flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
 
  
  fonts:
    - family: Sixtyfour
      fonts:
        - asset: assets/Sixtyfour-Regular.ttf
  
  
  
  
  
  
  
  
  
  
=======
name: flemini
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.6
  http: ^1.1.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  cloud_firestore: ^4.15.5
  intl: ^0.19.0
  image_picker: ^1.0.7
  flutter_gemini: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1
  icons_launcher: ^2.1.7
  

flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/animation/
    - assets/fonts/
   
 
  
  fonts:
    - family: Sixtyfour
      fonts:
        - asset: assets/fonts/Sixtyfour-Regular.ttf
  
  
  
  
  
  
  
  
  
  
>>>>>>> 8a78b94 (added)
