// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9EfSaOe8VTT2Y3AJD-n3iVCBsMFBuuo',
    appId: '1:590011864305:web:abe2a7969992f2557e4550',
    messagingSenderId: '590011864305',
    projectId: 'quik-ai',
    authDomain: 'quik-ai.firebaseapp.com',
    databaseURL: 'https://quik-ai-default-rtdb.firebaseio.com',
    storageBucket: 'quik-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWRnVf9ZKFALj5ceEgNi-1V2z7KyjwFeo',
    appId: '1:590011864305:android:bc50838b35adc4b37e4550',
    messagingSenderId: '590011864305',
    projectId: 'quik-ai',
    databaseURL: 'https://quik-ai-default-rtdb.firebaseio.com',
    storageBucket: 'quik-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjtGUe5hRlVmw2Q80prbURjZ6Ag5MqAT0',
    appId: '1:590011864305:ios:44d24e271bac1cf37e4550',
    messagingSenderId: '590011864305',
    projectId: 'quik-ai',
    databaseURL: 'https://quik-ai-default-rtdb.firebaseio.com',
    storageBucket: 'quik-ai.appspot.com',
    androidClientId: '590011864305-ddb3qoq3moc5ovjjfjd1382buakot8no.apps.googleusercontent.com',
    iosClientId: '590011864305-gih1edv54l760s1j28d0bsh06v2g1bbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.bardFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjtGUe5hRlVmw2Q80prbURjZ6Ag5MqAT0',
    appId: '1:590011864305:ios:7ff620cd34c3c64c7e4550',
    messagingSenderId: '590011864305',
    projectId: 'quik-ai',
    databaseURL: 'https://quik-ai-default-rtdb.firebaseio.com',
    storageBucket: 'quik-ai.appspot.com',
    androidClientId: '590011864305-ddb3qoq3moc5ovjjfjd1382buakot8no.apps.googleusercontent.com',
    iosClientId: '590011864305-t8tsrr80a7qbmucc6v4ugb1he0g5fktf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bardFlutter.RunnerTests',
  );
}
